// src/components/Form13/Form13.jsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import {form13API} from '../../services/form13API';
import TopNavDropdown from '../TopNavDropdown';
import masterData from '../../data/masterData';
import {
  isFieldRequired,
  getRequiredAttachments,
  getFieldLabel,
  validateFormData,
  isFieldVisible,
  getFieldDescription,
  needsNhavashevaCodeValidation,
  isEarlyGateInApplicable,
  isSpecialStowRequired,
  LOCATION_SPECIFIC_RULES,
  SHIPPING_LINE_RULES,
  CARGO_TYPE_RULES,
  ORIGIN_RULES
} from '../../utils/form13Validations';
import '../../styles/Form13.scss';

// MUI Icons
import {
  Save as SaveIcon,
  Send as SendIcon,
  Add as AddIcon,
  Remove as RemoveIcon,
  Info as InfoIcon,
  Error as ErrorIcon,
  CheckCircle as CheckCircleIcon,
  CloudUpload as CloudUploadIcon,
  AttachFile as AttachFileIcon,
  Warning as WarningIcon,
  ExpandMore as ExpandMoreIcon,
  ExpandLess as ExpandLessIcon,
  Visibility as VisibilityIcon,
  Delete as DeleteIcon,
  FileDownload as FileDownloadIcon,
  Print as PrintIcon,
  ArrowBack as ArrowBackIcon,
} from '@mui/icons-material';

const Form13 = () => {
  const { userData } = useAuth();
  const navigate = useNavigate();

  // Loading & Error States
  const [loading, setLoading] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [validationErrors, setValidationErrors] = useState({});
  const [schemaValidationErrors, setSchemaValidationErrors] = useState({});

  // Master Data States
  const [vessels, setVessels] = useState([]);
  const [pods, setPods] = useState([]);
  const [allPODs, setAllPODs] = useState([]);
  const [masterDataLoaded, setMasterDataLoaded] = useState(false);

  // UI States
  const [expandedSections, setExpandedSections] = useState({
    header: true,
    containers: true,
    attachments: true,
  });

  // Initial Form State - COMPLETE ACCORDING TO DOCUMENTATION
  const initialFormState = {
    // Header Section - All fields from API doc Section 5.3
    odexRefNo: '', // Optional - Generated by ODeX
    pyrCode: userData?.pyrCode || '', // Mandatory
    bnfCode: '', // Mandatory - Shipping Line
    locId: '', // Mandatory - Location
    vesselNm: '', // Mandatory - Vessel Name
    viaNo: '', // Conditional - VIA No
    terminalCode: '', // Mandatory - Terminal Code
    service: '', // Mandatory - Service
    pod: '', // Mandatory - POD
    fpod: '', // Conditional - Final POD (Chennai, Paradip, Kattupalli, Kolkata, Ennore)
    cargoTp: '', // Mandatory - Cargo Type
    origin: '', // Mandatory - Origin
    shpInstructNo: '', // Conditional - Shipping Instruction No (MSC)
    bookNo: '', // Conditional - Booking No (Mandatory for MSC)
    mobileNo: userData?.mobileNo || '', // Mandatory
    cfsCode: '', // Conditional - CFS Code (Required when Origin is Dock Destuff)
    issueTo: '', // Conditional - Issue To (Shipper, CHA Name)
    shipperNm: '', // Mandatory - Shipper Name
    consigneeNm: '', // Conditional - Required for Chennai, Paradip, Kattupalli, Kolkata, Ennore, Mundra
    consigneeAddr: '', // Conditional - Required for Chennai, Paradip, Kattupalli, Kolkata, Ennore, Mundra
    cargoDesc: '', // Conditional - Required for Chennai, Paradip, Kattupalli, Kolkata, Ennore, Mundra
    terminalLoginId: '', // Conditional - Required for Chennai, Paradip, Kattupalli, Kolkata, Ennore, Mundra
    emailId: '', // Optional - Email ID for notifications
    bookCopyBlNo: '', // Conditional - BL Number (Mandatory if Hapag Lloyd and cargo not Reefer)
    cntnrStatus: '', // Mandatory - Container Status (Full, Empty)
    formType: 'F13', // Mandatory - Form Type (F13, F11, CIO)
    IsEarlyGateIn: 'N', // Conditional - Early Gate In Check (Only for CMA line at Mundra)
    shipperCd: '', // Mandatory - Shipper Code (Auto populates)
    ShipperCity: '', // Conditional - Shipper City (F13 Tuticorin DBGT terminal mandatory)
    FFCode: '', // Conditional - FF Code (Required for Nhavasheva terminals)
    IECode: '', // Conditional - IE Code (Required for Nhavasheva terminals)
    CHACode: '', // Conditional - CHA Code (Required for Nhavasheva terminals)
    NotifyTO: '', // Optional - Notify To
    hashKey: '', // Conditional - Hash Key for encryption

    // Container Section - All fields from API doc Section 5.3 (Container Section)
    containers: [
      {
        cntnrReqId: '', // Container Request ID
        cntnrNo: '', // Mandatory - Container No (Format check required)
        cntnrSize: '', // Mandatory - Container Size
        iso: '', // Mandatory - ISO Code
        agentSealNo: '', // Mandatory - Agent Seal No
        customSealNo: '', // Mandatory - Custom Seal No
        vgmWt: '', // Conditional - VGM Weight (Required when VGM via ODeX is N)
        vgmViaODeX: 'N', // Mandatory - VGM via ODeX (Y/N)
        hsnCode: '', // Conditional - HSN Code (Mandatory if type is F11)
        commodityName: '', // Conditional - Commodity Name (Auto populates from HSN Code)
        doNo: '', // Optional - DO No
        temp: '', // Conditional - Temperature (Required when cargo Type is REF)
        volt: '', // Optional - Voltage
        imoNo1: '', // Conditional - IMO No (Required when cargo Type is HAZ)
        unNo1: '', // Conditional - UN No (Required when cargo Type is HAZ)
        imoNo2: '', // Optional - IMO No 1
        unNo2: '', // Optional - UN No 1
        imoNo3: '', // Optional - IMO No 2
        unNo3: '', // Optional - UN No 2
        imoNo4: '', // Optional - IMO No 3
        unNo4: '', // Optional - UN No 3
        rightDimensions: '', // Conditional - Right Dimensions (Required when cargo Type is ODC)
        topDimensions: '', // Conditional - Top Dimensions (Required when cargo Type is ODC)
        backDimensions: '', // Conditional - Back Dimensions (Required when cargo Type is ODC)
        leftDimensions: '', // Conditional - Left Dimensions (Required when cargo Type is ODC)
        frontDimensions: '', // Conditional - Front Dimensions (Required when cargo Type is ODC)
        odcUnits: '', // Conditional - ODC Units (Required when cargo Type is ODC)
        chaRemarks: '', // Optional - CHA Remarks
        vehicleNo: '', // Conditional - Vehicle No (Required for Mundra when Origin is Factory Stuffed or ICD by Road)
        driverLicNo: '', // Conditional - Driver License No
        driverNm: '', // Mandatory - Driver Name
        haulier: '', // Conditional - Haulier
        spclStow: '', // Conditional - Special Stow (Required for NSICT/NSIGT/BMCT)
        spclStowRemark: '', // Conditional - Special Stow Remarks (Required for NSICT/NSIGT/BMCT)
        status: 'REQUESTED', // Status
        SHIP_INSTRUCT_NO: '', // Conditional - Shipping Instruction No (Mandatory for MSC) - THIS WAS MISSING

        // Shipping Bill Details (sbDtlsVo array)
        sbDtlsVo: [
          {
            shipBillInvNo: '', // Mandatory - Shipping Bill/Invoice No
            shipBillDt: '', // Mandatory - Shipping Bill Date (YYYY-MM-DD HH:MM:SS)
            leoNo: '', // Optional - LEO No
            leoDt: '', // Conditional - LEO Date (YYYY-MM-DD HH:MM:SS)
            chaNm: userData?.pyrName || '', // Mandatory - CHA Name
            chaPan: '', // Mandatory - CHA PAN (5 letters + 4 digits + 1 letter)
            exporterNm: '', // Mandatory - Exporter Name
            exporterIec: '', // Mandatory - Exporter IEC (10 digits)
            noOfPkg: '', // Mandatory - No of Packages
          },
        ],
      },
    ],

    // Attachments Section
    attachments: [],
  };

  const [formData, setFormData] = useState(initialFormState);

  // ==============================================
  // MASTER DATA LOADING
  // ==============================================

  useEffect(() => {
    loadMasterData();
  }, []);

  const loadMasterData = async () => {
    try {
      setLoading(true);
      setError('');

      // Get user data
      const storedUserData = JSON.parse(localStorage.getItem('odex_auth'));
      const pyrCode = storedUserData?.userData?.pyrCode;

      if (!pyrCode) {
        throw new Error('Payor code not found. Please login again.');
      }

      const timestamp = new Date().toISOString().replace('T', ' ').split('.')[0];

      // Step 1: Get hash key from backend
      let hashKey;
      try {
        const hashKeyResponse = await form13API.getHashKey({
          pyrCode: pyrCode,
          timestamp: timestamp,
        });

        if (hashKeyResponse.data && hashKeyResponse.data.hashKey) {
          hashKey = hashKeyResponse.data.hashKey;
          console.log('Hash key received:', hashKey);
        } else {
          throw new Error('Hash key not received from server');
        }
      } catch (hashError) {
        console.error('Hash key error:', hashError);
        setError(`Failed to get hash key: ${hashError.response?.data?.error || hashError.message}`);
        setLoading(false);
        return;
      }

      // Store hashKey in formData for later use
      setFormData((prev) => ({
        ...prev,
        hashKey: hashKey,
        pyrCode: pyrCode,
      }));

      // Step 2: Load Vessel Master Data
      const vesselRequest = {
        pyrCode: pyrCode,
        fromTs: timestamp,
        hashKey: hashKey,
      };

      console.log('Vessel request payload:', vesselRequest);
      const vesselResponse = await form13API.getVesselMaster(vesselRequest);
      console.log('Vessel API response:', vesselResponse);

      if (vesselResponse.data && Array.isArray(vesselResponse.data)) {
        setVessels(vesselResponse.data);
        console.log('Vessels loaded:', vesselResponse.data.length);
      } else {
        console.warn('Vessel data not in expected format:', vesselResponse.data);
        setVessels([]);
      }

      // Step 3: Load POD Master Data
      const podRequest = {
        pyrCode: pyrCode,
        fromTs: timestamp,
        hashKey: hashKey,
      };

      console.log('POD request payload:', podRequest);
      const podResponse = await form13API.getPODMaster(podRequest);
      console.log('POD API response:', podResponse);

      if (podResponse.data && Array.isArray(podResponse.data)) {
        setPods(podResponse.data);
        console.log('PODs loaded:', podResponse.data.length);
        
        // Extract all PODs for dropdown
        const extractedPODs = extractAllPODs(podResponse.data);
        setAllPODs(extractedPODs);
      } else {
        console.warn('POD data not in expected format:', podResponse.data);
        setPods([]);
        setAllPODs([]);
      }

      setMasterDataLoaded(true);
      setSuccess('Master data loaded successfully');
    } catch (err) {
      console.error('Master data loading error:', err);
      setError(`Failed to load master data: ${err.response?.data?.error || err.message || 'Unknown error'}`);
    } finally {
      setLoading(false);
    }
  };

  // Extract all PODs from POD master data
  const extractAllPODs = (podData) => {
    const podOptions = [];
    const podSet = new Set();

    podData.forEach((location) => {
      location.terminal?.forEach((terminal) => {
        terminal.service?.forEach((service) => {
          service.pod?.forEach((pod) => {
            const podKey = `${pod.podCd}-${pod.podNm}`;
            if (!podSet.has(podKey) && pod.status === 'ACTIVE') {
              podSet.add(podKey);
              podOptions.push({
                value: pod.podCd,
                label: `${pod.podNm} (${pod.podCd})`,
                location: location.locId,
                terminal: terminal.terminalId,
                service: service.serviceNm,
                status: pod.status,
              });
            }
          });
        });
      });
    });

    return podOptions;
  };

  // ==============================================
  // FORM DATA HANDLERS
  // ==============================================

  const handleFormDataChange = (field, value, containerIndex = null, subField = null) => {
    setFormData((prev) => {
      let newData = { ...prev };

      if (containerIndex === null) {
        // Header field
        newData[field] = value;

        // Reset dependent fields when certain fields change
        if (field === 'locId') {
          newData.terminalCode = '';
          newData.service = '';
          newData.vesselNm = '';
          newData.viaNo = '';
          newData.pod = '';
          newData.fpod = '';
          newData.cfsCode = '';
        }

        if (field === 'bnfCode') {
          newData.vesselNm = '';
          newData.viaNo = '';
          newData.bookNo = '';
          newData.shpInstructNo = '';
          newData.bookCopyBlNo = '';
        }

        if (field === 'vesselNm') {
          // Find viaNo for selected vessel
          const selectedVessel = vessels.find(
            (v) => v.vesselNm === value && v.locId === newData.locId && v.bnfCode === newData.bnfCode
          );
          if (selectedVessel) {
            newData.viaNo = selectedVessel.viaNo;
            newData.terminalCode = selectedVessel.terminalCode;
            newData.service = selectedVessel.service;
          }
        }

        if (field === 'cargoTp') {
          // Reset cargo-specific fields
          newData.containers = newData.containers.map((container) => ({
            ...container,
            imoNo1: '',
            unNo1: '',
            imoNo2: '',
            unNo2: '',
            imoNo3: '',
            unNo3: '',
            imoNo4: '',
            unNo4: '',
            temp: '',
            rightDimensions: '',
            topDimensions: '',
            backDimensions: '',
            leftDimensions: '',
            frontDimensions: '',
            odcUnits: '',
          }));
        }

        if (field === 'origin') {
          newData.cfsCode = '';
          newData.containers = newData.containers.map((container) => ({
            ...container,
            vehicleNo: '',
          }));
        }
      } else {
        // Container field
        const newContainers = [...prev.containers];

        if (subField === null) {
          newContainers[containerIndex] = {
            ...newContainers[containerIndex],
            [field]: value,
          };
        } else {
          // Sub-field (e.g., sbDtlsVo)
          if (field === 'sbDtlsVo') {
            newContainers[containerIndex].sbDtlsVo[0] = {
              ...newContainers[containerIndex].sbDtlsVo[0],
              [subField]: value,
            };
          }
        }

        newData.containers = newContainers;
      }

      return newData;
    });
  };

  // ==============================================
  // CONTAINER MANAGEMENT
  // ==============================================

  const handleAddContainer = () => {
    setFormData((prev) => ({
      ...prev,
      containers: [
        ...prev.containers,
        {
          cntnrReqId: '',
          cntnrNo: '',
          cntnrSize: '',
          iso: '',
          agentSealNo: '',
          customSealNo: '',
          vgmWt: '',
          vgmViaODeX: 'N',
          hsnCode: '',
          commodityName: '',
          doNo: '',
          temp: '',
          volt: '',
          imoNo1: '',
          unNo1: '',
          imoNo2: '',
          unNo2: '',
          imoNo3: '',
          unNo3: '',
          imoNo4: '',
          unNo4: '',
          rightDimensions: '',
          topDimensions: '',
          backDimensions: '',
          leftDimensions: '',
          frontDimensions: '',
          odcUnits: '',
          chaRemarks: '',
          vehicleNo: '',
          driverLicNo: '',
          driverNm: '',
          haulier: '',
          spclStow: '',
          spclStowRemark: '',
          status: 'REQUESTED',
          SHIP_INSTRUCT_NO: '', // Added missing field
          sbDtlsVo: [
            {
              shipBillInvNo: '',
              shipBillDt: '',
              leoNo: '',
              leoDt: '',
              chaNm: userData?.pyrName || '',
              chaPan: '',
              exporterNm: '',
              exporterIec: '',
              noOfPkg: '',
            },
          ],
        },
      ],
    }));
  };

  const handleRemoveContainer = (index) => {
    if (formData.containers.length > 1) {
      setFormData((prev) => ({
        ...prev,
        containers: prev.containers.filter((_, i) => i !== index),
      }));
    }
  };

  // ==============================================
  // ATTACHMENT MANAGEMENT
  // ==============================================

  const handleAttachmentUpload = (event) => {
    const files = Array.from(event.target.files);

    const newAttachments = files.map((file) => ({
      file,
      name: file.name,
      type: file.type,
      size: file.size,
      title: 'BOOKING_COPY', // Default title
    }));

    setFormData((prev) => ({
      ...prev,
      attachments: [...prev.attachments, ...newAttachments],
    }));
  };

  const handleRemoveAttachment = (index) => {
    setFormData((prev) => ({
      ...prev,
      attachments: prev.attachments.filter((_, i) => i !== index),
    }));
  };

  const handleAttachmentTitleChange = (index, title) => {
    setFormData((prev) => {
      const newAttachments = [...prev.attachments];
      newAttachments[index].title = title;
      return {
        ...prev,
        attachments: newAttachments,
      };
    });
  };

  // ==============================================
  // VALIDATION
  // ==============================================

  const validateForm = () => {
    const errors = validateFormData(formData);
    
    // Filter out errors for fields that aren't visible/required
    const filteredErrors = {};
    Object.entries(errors).forEach(([key, error]) => {
      const shouldShowError = shouldValidateField(key, formData);
      if (shouldShowError) {
        filteredErrors[key] = error;
      }
    });

    return filteredErrors;
  };

  const shouldValidateField = (fieldKey, formData) => {
    // Handle attachments separately
    if (fieldKey === 'attachments') return true;

    // Extract field name and container index
    const isContainerField = fieldKey.startsWith('container_');
    if (isContainerField) {
      const match = fieldKey.match(/container_(\d+)_(.+)/);
      if (match) {
        const [, index, fieldName] = match;
        const containerIndex = parseInt(index);

        // Check field-specific conditions
        switch (fieldName) {
          case 'driverNm':
            return formData.origin === 'CFS';
          case 'temp':
            return formData.cargoTp === 'REEFER';
          case 'shipBillInvNo':
          case 'shipBillDt':
          case 'chaNm':
          case 'chaPan':
          case 'exporterNm':
          case 'exporterIec':
          case 'noOfPkg':
            return needsNhavashevaCodeValidation(formData);
          default:
            return true;
        }
      }
    }

    // For non-container fields, always validate
    return true;
  };

  // ==============================================
  // FORM SUBMISSION
  // ==============================================

  const handleSubmit = async () => {
    try {
      setSubmitting(true);
      setError('');
      setSuccess('');
      setValidationErrors({});
      setSchemaValidationErrors({});

      // Validate form
      const errors = validateForm();

      if (Object.keys(errors).length > 0) {
        setValidationErrors(errors);
        setError(`Please fix ${Object.keys(errors).length} validation errors before submitting`);
        
        // Scroll to first error
        const firstErrorKey = Object.keys(errors)[0];
        setTimeout(() => {
          const errorElement = document.querySelector(`[data-field="${firstErrorKey}"]`);
          if (errorElement) {
            errorElement.scrollIntoView({ behavior: 'smooth', block: 'center' });
            errorElement.focus();
          }
        }, 100);

        setSubmitting(false);
        return;
      }

      // Ensure we have hash key
      if (!formData.hashKey) {
        setError('Hash key is missing. Please reload the page and try again.');
        setSubmitting(false);
        return;
      }

      // Prepare payload with hash key
      const payload = {
        formType: 'F13',
        bookNo: formData.bookNo,
        bnfCode: formData.bnfCode,
        locId: formData.locId,
        vesselNm: formData.vesselNm,
        viaNo: formData.viaNo,
        terminalCode: formData.terminalCode,
        service: formData.service,
        pod: formData.pod,
        fpod: formData.fpod,
        cargoTp: formData.cargoTp,
        origin: formData.origin,
        shpInstructNo: formData.shpInstructNo,
        cntnrStatus: formData.cntnrStatus,
        mobileNo: formData.mobileNo,
        issueTo: formData.issueTo,
        shipperNm: formData.shipperNm,
        pyrCode: formData.pyrCode,
        consigneeNm: formData.consigneeNm,
        consigneeAddr: formData.consigneeAddr,
        cargoDesc: formData.cargoDesc,
        terminalLoginId: formData.terminalLoginId,
        isEarlyGateIn: formData.IsEarlyGateIn,
        shipperCd: formData.shipperCd,
        shipperCity: formData.ShipperCity,
        ffCode: formData.FFCode,
        ieCode: formData.IECode,
        chaCode: formData.CHACode,
        notifyTo: formData.NotifyTO,
        hashKey: formData.hashKey, // Make sure hash key is included
        
        cntrList: formData.containers.map((container, index) => ({
          cntnrReqId: container.cntnrReqId || `CONTAINER_${index + 1}`,
          cntnrNo: container.cntnrNo,
          cntnrSize: container.cntnrSize,
          iso: container.iso,
          agentSealNo: container.agentSealNo,
          customSealNo: container.customSealNo,
          vgmWt: container.vgmWt,
          vgmViaODeX: container.vgmViaODeX,
          doNo: container.doNo,
          temp: container.temp,
          volt: container.volt,
          chaRemarks: container.chaRemarks,
          vehicleNo: container.vehicleNo,
          driverLicNo: container.driverLicNo,
          driverNm: container.driverNm,
          haulier: container.haulier,
          imoNo1: container.imoNo1,
          unNo1: container.unNo1,
          imoNo2: container.imoNo2,
          unNo2: container.unNo2,
          imoNo3: container.imoNo3,
          unNo3: container.unNo3,
          imoNo4: container.imoNo4,
          unNo4: container.unNo4,
          rightDimensions: container.rightDimensions,
          topDimensions: container.topDimensions,
          backDimensions: container.backDimensions,
          leftDimensions: container.leftDimensions,
          frontDimensions: container.frontDimensions,
          odcUnits: container.odcUnits,
          status: container.status,
          spclStow: container.spclStow,
          spclStowRemark: container.spclStowRemark,
          shpInstructNo: container.SHIP_INSTRUCT_NO, // Map to correct field
          hsnCode: container.hsnCode,
          commodityName: container.commodityName,
          sbDtlsVo: container.sbDtlsVo,
        })),

        attList: await Promise.all(
          formData.attachments.map(async (att) => ({
            attReqID: '',
            attNm: att.name,
            attData: await fileToBase64(att.file),
            attTitle: att.title,
          }))
        ),
      };

      console.log('Submitting payload:', payload);

      // Call API
      const response = await form13API.submitForm13(payload);
      console.log('Submit response:', response);

      if (response.data && response.data.odexRefNo) {
        setSuccess(`Form 13 submitted successfully! Reference No: ${response.data.odexRefNo}`);
        
        // Reset form after successful submission
        setTimeout(() => {
          setFormData({
            ...initialFormState,
            pyrCode: userData?.pyrCode,
            hashKey: formData.hashKey, // Preserve hash key
          });
        }, 3000);
      } else {
        setError('Submission failed. Please try again.');
      }
    } catch (err) {
      console.error('Submission error:', err);
      setError(err.response?.data?.error || err.message || 'Submission failed');
    } finally {
      setSubmitting(false);
    }
  };

  // ==============================================
  // HELPER FUNCTIONS
  // ==============================================

  const fileToBase64 = (file) => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => resolve(reader.result.split(',')[1]);
      reader.onerror = (error) => reject(error);
    });
  };

  const toggleSection = (section) => {
    setExpandedSections((prev) => ({
      ...prev,
      [section]: !prev[section],
    }));
  };

  const hasFieldError = (fieldName, containerIndex = null) => {
    const errorKey = containerIndex !== null ? `container_${containerIndex}_${fieldName}` : fieldName;
    return !!(validationErrors[errorKey] || schemaValidationErrors[errorKey]);
  };

  const getFieldError = (fieldName, containerIndex = null) => {
    const errorKey = containerIndex !== null ? `container_${containerIndex}_${fieldName}` : fieldName;
    return validationErrors[errorKey] || schemaValidationErrors[errorKey];
  };

  const renderFieldIndicator = (fieldName, containerIndex = null) => {
    const isRequired = isFieldRequired(fieldName, formData, containerIndex);
    const errorKey = containerIndex !== null ? `container_${containerIndex}_${fieldName}` : fieldName;
    const hasError = validationErrors[errorKey];
    const description = getFieldDescription(fieldName);

    return (
      <span className="d-flex gap-1">
        {isRequired && <span className="required">*</span>}
        {description && (
          <span className="field-info-icon" title={description}>
            <InfoIcon style={{ fontSize: 14, color: '#64748b', cursor: 'help' }} />
          </span>
        )}
        {hasError && (
          <span className="error-icon" title={hasError}>
            <ErrorIcon style={{ fontSize: 14, color: '#dc2626' }} />
          </span>
        )}
      </span>
    );
  };

  const getFilteredPODs = () => {
    const { locId, terminalCode, service } = formData;

    if (!locId) return allPODs;

    // Filter PODs based on location, terminal, and service
    const locationData = pods.find((p) => p.locId === locId);
    if (!locationData) return allPODs;

    const terminalData = locationData.terminal?.find((t) => t.terminalId === terminalCode);
    if (!terminalData || !terminalCode) return allPODs;

    const serviceData = terminalData.service?.find((s) => s.serviceNm === service);
    if (!serviceData || !service) return allPODs;

    if (serviceData.pod) {
      return serviceData.pod
        .filter((pod) => pod.status === 'ACTIVE')
        .map((pod) => ({
          value: pod.podCd,
          label: `${pod.podNm} (${pod.podCd})`,
        }));
    }

    return allPODs;
  };

  const formatFileSize = (bytes) => {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
  };

  // Get required attachments
  const requiredAttachments = getRequiredAttachments(formData);

  // ==============================================
  // RENDER
  // ==============================================

  if (loading) {
    return (
      <div className="loading">
        <div className="spinner"></div>
        <span>Loading master data...</span>
      </div>
    );
  }

  return (
    <div className="form13-container">
      {/* Top Navigation */}
      <TopNavDropdown />

      {/* Header */}
      <div className="page-header">
        <div>
          <h2>Export Gate Pass - Form 13</h2>
          <div className="d-flex gap-2 mt-1">
            <span className="header-meta">Payor: {userData?.pyrName || 'N/A'}</span>
            <span className="header-meta">Code: {userData?.pyrCode || 'N/A'}</span>
            {masterDataLoaded && <span className="badge badge-success">Master Data Loaded</span>}
          </div>
        </div>
        <div className="d-flex gap-2">
          <button className="btn btn-outline" onClick={() => window.print()}>
            <PrintIcon fontSize="small" /> Print
          </button>
          <button className="btn btn-outline" onClick={() => navigate(-1)}>
            <ArrowBackIcon fontSize="small" /> Back
          </button>
        </div>
      </div>

      {/* Error/Success Messages */}
      {error && (
        <div className="alert alert-error">
          <ErrorIcon fontSize="small" />
          <span>{error}</span>
          <button className="btn btn-icon ml-2" onClick={() => setError('')} style={{ marginLeft: 'auto' }}></button>
        </div>
      )}

      {success && (
        <div className="alert alert-success">
          <CheckCircleIcon fontSize="small" />
          <span>{success}</span>
          <button className="btn btn-icon ml-2" onClick={() => setSuccess('')} style={{ marginLeft: 'auto' }}></button>
        </div>
      )}

      {/* Main Form Sections */}
      <div className="form-sections">
        {/* HEADER SECTION */}
        <div className="panel">
          <div
            className="panel-title d-flex justify-between"
            onClick={() => toggleSection('header')}
            style={{ cursor: 'pointer' }}
          >
            <span>Header Information</span>
            <span>
              {expandedSections.header ? (
                <ExpandLessIcon fontSize="small" />
              ) : (
                <ExpandMoreIcon fontSize="small" />
              )}
            </span>
          </div>

          {expandedSections.header && (
            <div className="form-grid">
              {/* Location & Shipping Line */}
              <div className="form-group">
                <label>
                  Location {renderFieldIndicator('locId')}
                </label>
                <select
                  className={`form-control ${validationErrors.locId ? 'error' : ''}`}
                  value={formData.locId}
                  onChange={(e) => handleFormDataChange('locId', e.target.value)}
                >
                  <option value="">Select Location</option>
                  {/* Extract unique locations from vessels */}
                  {Array.from(new Set(vessels.map((v) => v.locId)))
                    .filter((locId) => locId) // Remove null/undefined
                    .map((locId) => {
                      const vessel = vessels.find((v) => v.locId === locId);
                      return (
                        <option key={locId} value={locId}>
                          {vessel?.locNm || locId}
                        </option>
                      );
                    })}
                </select>
                {validationErrors.locId && <div className="error-text">{validationErrors.locId}</div>}
              </div>

              <div className="form-group">
                <label>
                  Shipping Line {renderFieldIndicator('bnfCode')}
                </label>
                <select
                  className={`form-control ${validationErrors.bnfCode ? 'error' : ''}`}
                  value={formData.bnfCode}
                  onChange={(e) => handleFormDataChange('bnfCode', e.target.value)}
                >
                  <option value="">Select Shipping Line</option>
                  {/* Extract unique shipping lines from vessels */}
                  {Array.from(new Set(vessels.map((v) => v.bnfCode)))
                    .filter((bnfCode) => bnfCode) // Remove null/undefined
                    .map((bnfCode) => {
                      const vessel = vessels.find((v) => v.bnfCode === bnfCode);
                      return (
                        <option key={bnfCode} value={bnfCode}>
                          {vessel?.bnfNm || bnfCode}
                        </option>
                      );
                    })}
                </select>
                {validationErrors.bnfCode && <div className="error-text">{validationErrors.bnfCode}</div>}
              </div>

              {/* Vessel Information */}
              <div className="form-group">
                <label>
                  Vessel Name {renderFieldIndicator('vesselNm')}
                </label>
                <select
                  className={`form-control ${validationErrors.vesselNm ? 'error' : ''}`}
                  value={formData.vesselNm}
                  onChange={(e) => handleFormDataChange('vesselNm', e.target.value)}
                  disabled={!formData.locId || !formData.bnfCode}
                >
                  <option value="">Select Vessel</option>
                  {vessels
                    .filter((v) => v.locId === formData.locId && v.bnfCode === formData.bnfCode)
                    .map((vessel) => (
                      <option key={vessel.vesselId} value={vessel.vesselNm}>
                        {vessel.vesselNm}
                      </option>
                    ))}
                </select>
                {validationErrors.vesselNm && <div className="error-text">{validationErrors.vesselNm}</div>}
              </div>

              <div className="form-group">
                <label>VIA No</label>
                <input type="text" className="form-control" value={formData.viaNo} readOnly />
              </div>

              {/* Terminal & Service */}
              <div className="form-group">
                <label>Terminal</label>
                <input type="text" className="form-control" value={formData.terminalCode} readOnly />
              </div>

              <div className="form-group">
                <label>Service</label>
                <input type="text" className="form-control" value={formData.service} readOnly />
              </div>

              {/* POD & FPOD */}
              <div className="form-group">
                <label>
                  POD {renderFieldIndicator('pod')}
                </label>
                <select
                  className={`form-control ${validationErrors.pod ? 'error' : ''}`}
                  value={formData.pod}
                  onChange={(e) => handleFormDataChange('pod', e.target.value)}
                  disabled={!formData.locId}
                >
                  <option value="">Select POD</option>
                  {getFilteredPODs().map((pod) => (
                    <option key={pod.value} value={pod.value}>
                      {pod.label}
                    </option>
                  ))}
                </select>
                {validationErrors.pod && <div className="error-text">{validationErrors.pod}</div>}
              </div>

              {/* FPOD - Show only for specific locations */}
              {['INMAA1', 'INPRT1', 'INKAT1', 'INCCU1', 'INENN1'].includes(formData.locId) && (
                <div className="form-group">
                  <label>
                    Final POD {renderFieldIndicator('fpod')}
                  </label>
                  <input
                    type="text"
                    className={`form-control ${validationErrors.fpod ? 'error' : ''}`}
                    value={formData.fpod}
                    onChange={(e) => handleFormDataChange('fpod', e.target.value)}
                  />
                  {validationErrors.fpod && <div className="error-text">{validationErrors.fpod}</div>}
                </div>
              )}

              {/* Cargo & Origin */}
              <div className="form-group">
                <label>
                  Cargo Type {renderFieldIndicator('cargoTp')}
                </label>
                <select
                  className={`form-control ${validationErrors.cargoTp ? 'error' : ''}`}
                  value={formData.cargoTp}
                  onChange={(e) => handleFormDataChange('cargoTp', e.target.value)}
                >
                  <option value="">Select Cargo Type</option>
                  {masterData.cargoTypes &&
                    masterData.cargoTypes.map((type) => (
                      <option key={type.value} value={type.value}>
                        {type.label}
                      </option>
                    ))}
                </select>
                {validationErrors.cargoTp && <div className="error-text">{validationErrors.cargoTp}</div>}
              </div>

              <div className="form-group">
                <label>
                  Origin {renderFieldIndicator('origin')}
                </label>
                <select
                  className={`form-control ${validationErrors.origin ? 'error' : ''}`}
                  value={formData.origin}
                  onChange={(e) => handleFormDataChange('origin', e.target.value)}
                >
                  <option value="">Select Origin</option>
                  {masterData.originTypes &&
                    masterData.originTypes.map((origin) => (
                      <option key={origin.value} value={origin.value}>
                        {origin.label}
                      </option>
                    ))}
                </select>
                {validationErrors.origin && <div className="error-text">{validationErrors.origin}</div>}
              </div>

              {/* Booking Details - Show for MSC */}
              {formData.bnfCode?.toUpperCase() === 'MSCU' && (
                <>
                  <div className="form-group">
                    <label>
                      Shipping Instruction No {renderFieldIndicator('shpInstructNo')}
                    </label>
                    <input
                      type="text"
                      className={`form-control ${validationErrors.shpInstructNo ? 'error' : ''}`}
                      value={formData.shpInstructNo}
                      onChange={(e) => handleFormDataChange('shpInstructNo', e.target.value)}
                      data-field="shpInstructNo"
                    />
                    {validationErrors.shpInstructNo && (
                      <div className="error-text">{validationErrors.shpInstructNo}</div>
                    )}
                  </div>

                  <div className="form-group">
                    <label>
                      Booking No {renderFieldIndicator('bookNo')}
                    </label>
                    <input
                      type="text"
                      className={`form-control ${validationErrors.bookNo ? 'error' : ''}`}
                      value={formData.bookNo}
                      onChange={(e) => handleFormDataChange('bookNo', e.target.value)}
                    />
                    {validationErrors.bookNo && <div className="error-text">{validationErrors.bookNo}</div>}
                  </div>
                </>
              )}

              {/* BL Number - Show for Hapag Lloyd non-reefer */}
              {formData.bnfCode?.toUpperCase().includes('HAPAG') && formData.cargoTp !== 'REF' && (
                <div className="form-group">
                  <label>
                    BL Number {renderFieldIndicator('bookCopyBlNo')}
                  </label>
                  <input
                    type="text"
                    className={`form-control ${validationErrors.bookCopyBlNo ? 'error' : ''}`}
                    value={formData.bookCopyBlNo}
                    onChange={(e) => handleFormDataChange('bookCopyBlNo', e.target.value)}
                  />
                  {validationErrors.bookCopyBlNo && <div className="error-text">{validationErrors.bookCopyBlNo}</div>}
                </div>
              )}

              {/* Container Status */}
              <div className="form-group">
                <label>
                  Container Status {renderFieldIndicator('cntnrStatus')}
                </label>
                <select
                  className={`form-control ${validationErrors.cntnrStatus ? 'error' : ''}`}
                  value={formData.cntnrStatus}
                  onChange={(e) => handleFormDataChange('cntnrStatus', e.target.value)}
                >
                  <option value="">Select Status</option>
                  <option value="FULL">Full</option>
                  <option value="EMPTY">Empty</option>
                  <option value="MT">MT</option>
                  <option value="ODC">ODC</option>
                </select>
                {validationErrors.cntnrStatus && <div className="error-text">{validationErrors.cntnrStatus}</div>}
              </div>

              {/* Contact Information */}
              <div className="form-group">
                <label>
                  Mobile No {renderFieldIndicator('mobileNo')}
                </label>
                <input
                  type="tel"
                  className={`form-control ${validationErrors.mobileNo ? 'error' : ''}`}
                  value={formData.mobileNo}
                  onChange={(e) => handleFormDataChange('mobileNo', e.target.value)}
                />
                {validationErrors.mobileNo && <div className="error-text">{validationErrors.mobileNo}</div>}
              </div>

              <div className="form-group">
                <label>Issue To</label>
                <input
                  type="text"
                  className="form-control"
                  value={formData.issueTo}
                  onChange={(e) => handleFormDataChange('issueTo', e.target.value)}
                />
              </div>

              {/* Shipper & Consignee */}
              <div className="form-group">
                <label>Shipper Name</label>
                <input
                  type="text"
                  className="form-control"
                  value={formData.shipperNm}
                  onChange={(e) => handleFormDataChange('shipperNm', e.target.value)}
                />
              </div>

              {/* Show consignee fields for specific locations */}
              {['INMAA1', 'INPRT1', 'INKAT1', 'INCCU1', 'INENN1', 'INMUN1'].includes(formData.locId) && (
                <>
                  <div className="form-group">
                    <label>
                      Consignee Name {renderFieldIndicator('consigneeNm')}
                    </label>
                    <input
                      type="text"
                      className={`form-control ${validationErrors.consigneeNm ? 'error' : ''}`}
                      value={formData.consigneeNm}
                      onChange={(e) => handleFormDataChange('consigneeNm', e.target.value)}
                    />
                    {validationErrors.consigneeNm && <div className="error-text">{validationErrors.consigneeNm}</div>}
                  </div>

                  <div className="form-group">
                    <label>Consignee Address</label>
                    <textarea
                      className="form-control"
                      value={formData.consigneeAddr}
                      onChange={(e) => handleFormDataChange('consigneeAddr', e.target.value)}
                      rows={3}
                    />
                  </div>

                  <div className="form-group">
                    <label>Cargo Description</label>
                    <textarea
                      className="form-control"
                      value={formData.cargoDesc}
                      onChange={(e) => handleFormDataChange('cargoDesc', e.target.value)}
                      rows={2}
                    />
                  </div>

                  <div className="form-group">
                    <label>Terminal Login ID</label>
                    <input
                      type="text"
                      className="form-control"
                      value={formData.terminalLoginId}
                      onChange={(e) => handleFormDataChange('terminalLoginId', e.target.value)}
                    />
                  </div>
                </>
              )}

              {/* CFS Code - Show when origin is Dock Destuff */}
              {formData.origin === 'C' && (
                <div className="form-group">
                  <label>CFS Code</label>
                  <input
                    type="text"
                    className="form-control"
                    value={formData.cfsCode}
                    onChange={(e) => handleFormDataChange('cfsCode', e.target.value)}
                  />
                </div>
              )}

              {/* Early Gate In - Show for CMA at Mundra */}
              {isEarlyGateInApplicable(formData) && (
                <div className="form-group">
                  <label>Early Gate In</label>
                  <div className="radio-group">
                    <label>
                      <input
                        type="radio"
                        name="IsEarlyGateIn"
                        value="Y"
                        checked={formData.IsEarlyGateIn === 'Y'}
                        onChange={(e) => handleFormDataChange('IsEarlyGateIn', e.target.value)}
                      />
                      Yes
                    </label>
                    <label>
                      <input
                        type="radio"
                        name="IsEarlyGateIn"
                        value="N"
                        checked={formData.IsEarlyGateIn === 'N'}
                        onChange={(e) => handleFormDataChange('IsEarlyGateIn', e.target.value)}
                      />
                      No
                    </label>
                  </div>
                </div>
              )}

              {/* Shipper City - Show for Tuticorin DBGT */}
              {formData.locId === 'INTUT1' && formData.terminalCode === 'DBGT' && (
                <div className="form-group">
                  <label>
                    Shipper City {renderFieldIndicator('ShipperCity')}
                  </label>
                  <input
                    type="text"
                    className="form-control"
                    value={formData.ShipperCity}
                    onChange={(e) => handleFormDataChange('ShipperCity', e.target.value)}
                  />
                </div>
              )}

              {/* Email & Notify To */}
              <div className="form-group">
                <label>Email ID</label>
                <input
                  type="email"
                  className="form-control"
                  value={formData.emailId}
                  onChange={(e) => handleFormDataChange('emailId', e.target.value)}
                />
              </div>

              <div className="form-group">
                <label>Notify To</label>
                <input
                  type="text"
                  className="form-control"
                  value={formData.NotifyTO}
                  onChange={(e) => handleFormDataChange('NotifyTO', e.target.value)}
                />
              </div>

              {/* Code Fields - Show for Nhavasheva */}
              {formData.locId === 'INNSA1' && (
                <>
                  <div className="form-group">
                    <label>FF Code</label>
                    <input
                      type="text"
                      className="form-control"
                      value={formData.FFCode}
                      onChange={(e) => handleFormDataChange('FFCode', e.target.value)}
                    />
                  </div>

                  <div className="form-group">
                    <label>IE Code</label>
                    <input
                      type="text"
                      className="form-control"
                      value={formData.IECode}
                      onChange={(e) => handleFormDataChange('IECode', e.target.value)}
                    />
                  </div>

                  <div className="form-group">
                    <label>CHA Code</label>
                    <input
                      type="text"
                      className="form-control"
                      value={formData.CHACode}
                      onChange={(e) => handleFormDataChange('CHACode', e.target.value)}
                    />
                  </div>
                </>
              )}

              <div className="form-group">
                <label>Shipper Code</label>
                <input
                  type="text"
                  className="form-control"
                  value={formData.shipperCd}
                  onChange={(e) => handleFormDataChange('shipperCd', e.target.value)}
                />
              </div>
            </div>
          )}
        </div>

        {/* CONTAINER SECTION */}
        <div className="panel">
          <div
            className="panel-title d-flex justify-between"
            onClick={() => toggleSection('containers')}
            style={{ cursor: 'pointer' }}
          >
            <div className="d-flex gap-2">
              <span>Container Details</span>
              <span className="badge badge-info">{formData.containers.length} Container(s)</span>
            </div>
            <div className="d-flex gap-2">
              <button
                className="btn btn-icon btn-outline"
                onClick={(e) => {
                  e.stopPropagation();
                  handleAddContainer();
                }}
                title="Add Container"
              >
                <AddIcon fontSize="small" />
              </button>
              <span>
                {expandedSections.containers ? (
                  <ExpandLessIcon fontSize="small" />
                ) : (
                  <ExpandMoreIcon fontSize="small" />
                )}
              </span>
            </div>
          </div>

          {expandedSections.containers && (
            <div>
              {formData.containers.map((container, containerIndex) => (
                <div key={containerIndex} className="container-card mb-3">
                  <div className="container-header">
                    <h3>Container {containerIndex + 1}</h3>
                    <div className="container-actions">
                      {formData.containers.length > 1 && (
                        <button
                          className="btn btn-icon btn-outline"
                          onClick={() => handleRemoveContainer(containerIndex)}
                          title="Remove Container"
                        >
                          <RemoveIcon fontSize="small" />
                        </button>
                      )}
                    </div>
                  </div>

                  <div className="container-body">
                    <div className="form-grid">
                      {/* Container Basic Info */}
                      <div className="form-group">
                        <label>
                          Container No {renderFieldIndicator('cntnrNo', containerIndex)}
                        </label>
                        <input
                          type="text"
                          className={`form-control ${hasFieldError('cntnrNo', containerIndex) ? 'error' : ''}`}
                          value={container.cntnrNo}
                          onChange={(e) => handleFormDataChange('cntnrNo', e.target.value, containerIndex)}
                        />
                        {hasFieldError('cntnrNo', containerIndex) && (
                          <div className="error-text">{getFieldError('cntnrNo', containerIndex)}</div>
                        )}
                      </div>

                      <div className="form-group">
                        <label>
                          Container Size {renderFieldIndicator('cntnrSize', containerIndex)}
                        </label>
                        <select
                          className={`form-control ${hasFieldError('cntnrSize', containerIndex) ? 'error' : ''}`}
                          value={container.cntnrSize}
                          onChange={(e) => handleFormDataChange('cntnrSize', e.target.value, containerIndex)}
                        >
                          <option value="">Select Size</option>
                          {masterData.containerSizes &&
                            masterData.containerSizes.map((size) => (
                              <option key={size.value} value={size.value}>
                                {size.label}
                              </option>
                            ))}
                        </select>
                        {hasFieldError('cntnrSize', containerIndex) && (
                          <div className="error-text">{getFieldError('cntnrSize', containerIndex)}</div>
                        )}
                      </div>

                      <div className="form-group">
                        <label>ISO Code</label>
                        <input
                          type="text"
                          className="form-control"
                          value={container.iso}
                          onChange={(e) => handleFormDataChange('iso', e.target.value, containerIndex)}
                        />
                      </div>

                      {/* Seal Numbers */}
                      <div className="form-group">
                        <label>Agent Seal No</label>
                        <input
                          type="text"
                          className="form-control"
                          value={container.agentSealNo}
                          onChange={(e) => handleFormDataChange('agentSealNo', e.target.value, containerIndex)}
                        />
                      </div>

                      <div className="form-group">
                        <label>Custom Seal No</label>
                        <input
                          type="text"
                          className="form-control"
                          value={container.customSealNo}
                          onChange={(e) => handleFormDataChange('customSealNo', e.target.value, containerIndex)}
                        />
                      </div>

                      {/* VGM */}
                      <div className="form-group">
                        <label>
                          VGM Weight (KGS) {renderFieldIndicator('vgmWt', containerIndex)}
                        </label>
                        <input
                          type="number"
                          className={`form-control ${hasFieldError('vgmWt', containerIndex) ? 'error' : ''}`}
                          value={container.vgmWt}
                          onChange={(e) => handleFormDataChange('vgmWt', e.target.value, containerIndex)}
                          step="0.01"
                        />
                        {hasFieldError('vgmWt', containerIndex) && (
                          <div className="error-text">{getFieldError('vgmWt', containerIndex)}</div>
                        )}
                      </div>

                      <div className="form-group">
                        <label>VGM via ODeX</label>
                        <div className="radio-group">
                          <label>
                            <input
                              type="radio"
                              name={`vgmViaODeX_${containerIndex}`}
                              value="Y"
                              checked={container.vgmViaODeX === 'Y'}
                              onChange={(e) => handleFormDataChange('vgmViaODeX', e.target.value, containerIndex)}
                            />
                            Yes
                          </label>
                          <label>
                            <input
                              type="radio"
                              name={`vgmViaODeX_${containerIndex}`}
                              value="N"
                              checked={container.vgmViaODeX === 'N'}
                              onChange={(e) => handleFormDataChange('vgmViaODeX', e.target.value, containerIndex)}
                            />
                            No
                          </label>
                        </div>
                      </div>

                      {/* DO No */}
                      <div className="form-group">
                        <label>DO No</label>
                        <input
                          type="text"
                          className="form-control"
                          value={container.doNo}
                          onChange={(e) => handleFormDataChange('doNo', e.target.value, containerIndex)}
                        />
                      </div>

                      {/* Temperature - Only show for Reefer cargo */}
                      {formData.cargoTp === 'REF' && (
                        <div className="form-group">
                          <label>
                            Temperature (°C) {renderFieldIndicator('temp', containerIndex)}
                          </label>
                          <input
                            type="number"
                            className={`form-control ${hasFieldError('temp', containerIndex) ? 'error' : ''}`}
                            value={container.temp}
                            onChange={(e) => handleFormDataChange('temp', e.target.value, containerIndex)}
                          />
                          {hasFieldError('temp', containerIndex) && (
                            <div className="error-text">{getFieldError('temp', containerIndex)}</div>
                          )}
                        </div>
                      )}

                      {/* Voltage */}
                      <div className="form-group">
                        <label>Voltage</label>
                        <input
                          type="number"
                          className="form-control"
                          value={container.volt}
                          onChange={(e) => handleFormDataChange('volt', e.target.value, containerIndex)}
                        />
                      </div>

                      {/* Dangerous Goods - Only show for dangerous cargo */}
                      {['HAZ', 'ODC(HAZ)', 'REF(HAZ)', 'FLT(HAZ)'].includes(formData.cargoTp) && (
                        <>
                          <div className="form-group">
                            <label>IMO No 1</label>
                            <input
                              type="text"
                              className="form-control"
                              value={container.imoNo1}
                              onChange={(e) => handleFormDataChange('imoNo1', e.target.value, containerIndex)}
                            />
                          </div>

                          <div className="form-group">
                            <label>UN No 1</label>
                            <input
                              type="text"
                              className="form-control"
                              value={container.unNo1}
                              onChange={(e) => handleFormDataChange('unNo1', e.target.value, containerIndex)}
                            />
                          </div>

                          <div className="form-group">
                            <label>IMO No 2</label>
                            <input
                              type="text"
                              className="form-control"
                              value={container.imoNo2}
                              onChange={(e) => handleFormDataChange('imoNo2', e.target.value, containerIndex)}
                            />
                          </div>

                          <div className="form-group">
                            <label>UN No 2</label>
                            <input
                              type="text"
                              className="form-control"
                              value={container.unNo2}
                              onChange={(e) => handleFormDataChange('unNo2', e.target.value, containerIndex)}
                            />
                          </div>

                          <div className="form-group">
                            <label>IMO No 3</label>
                            <input
                              type="text"
                              className="form-control"
                              value={container.imoNo3}
                              onChange={(e) => handleFormDataChange('imoNo3', e.target.value, containerIndex)}
                            />
                          </div>

                          <div className="form-group">
                            <label>UN No 3</label>
                            <input
                              type="text"
                              className="form-control"
                              value={container.unNo3}
                              onChange={(e) => handleFormDataChange('unNo3', e.target.value, containerIndex)}
                            />
                          </div>

                          <div className="form-group">
                            <label>IMO No 4</label>
                            <input
                              type="text"
                              className="form-control"
                              value={container.imoNo4}
                              onChange={(e) => handleFormDataChange('imoNo4', e.target.value, containerIndex)}
                            />
                          </div>

                          <div className="form-group">
                            <label>UN No 4</label>
                            <input
                              type="text"
                              className="form-control"
                              value={container.unNo4}
                              onChange={(e) => handleFormDataChange('unNo4', e.target.value, containerIndex)}
                            />
                          </div>
                        </>
                      )}

                      {/* ODC Dimensions - Only show for ODC cargo */}
                      {['ODC', 'ODC(HAZ)'].includes(formData.cargoTp) && (
                        <>
                          <div className="form-group">
                            <label>Right Dimensions</label>
                            <input
                              type="text"
                              className="form-control"
                              value={container.rightDimensions}
                              onChange={(e) => handleFormDataChange('rightDimensions', e.target.value, containerIndex)}
                            />
                          </div>

                          <div className="form-group">
                            <label>Top Dimensions</label>
                            <input
                              type="text"
                              className="form-control"
                              value={container.topDimensions}
                              onChange={(e) => handleFormDataChange('topDimensions', e.target.value, containerIndex)}
                            />
                          </div>

                          <div className="form-group">
                            <label>Back Dimensions</label>
                            <input
                              type="text"
                              className="form-control"
                              value={container.backDimensions}
                              onChange={(e) => handleFormDataChange('backDimensions', e.target.value, containerIndex)}
                            />
                          </div>

                          <div className="form-group">
                            <label>Left Dimensions</label>
                            <input
                              type="text"
                              className="form-control"
                              value={container.leftDimensions}
                              onChange={(e) => handleFormDataChange('leftDimensions', e.target.value, containerIndex)}
                            />
                          </div>

                          <div className="form-group">
                            <label>Front Dimensions</label>
                            <input
                              type="text"
                              className="form-control"
                              value={container.frontDimensions}
                              onChange={(e) => handleFormDataChange('frontDimensions', e.target.value, containerIndex)}
                            />
                          </div>

                          <div className="form-group">
                            <label>ODC Units</label>
                            <input
                              type="number"
                              className="form-control"
                              value={container.odcUnits}
                              onChange={(e) => handleFormDataChange('odcUnits', e.target.value, containerIndex)}
                            />
                          </div>
                        </>
                      )}

                      {/* Special Stowage - Show for NSICT/NSIGT/BMCT terminals */}
                      {isSpecialStowRequired(formData.locId, formData.terminalCode) && (
                        <>
                          <div className="form-group">
                            <label>Special Stow</label>
                            <select
                              className="form-control"
                              value={container.spclStow}
                              onChange={(e) => handleFormDataChange('spclStow', e.target.value, containerIndex)}
                            >
                              <option value="">Select Option</option>
                              <option value="Y">Yes</option>
                              <option value="N">No</option>
                            </select>
                          </div>

                          {container.spclStow === 'Y' && (
                            <div className="form-group">
                              <label>Special Stow Remarks</label>
                              <textarea
                                className="form-control"
                                value={container.spclStowRemark}
                                onChange={(e) =>
                                  handleFormDataChange('spclStowRemark', e.target.value, containerIndex)
                                }
                                rows={2}
                              />
                            </div>
                          )}
                        </>
                      )}

                      {/* Transport Details for CFS origin or Mundra */}
                      {(formData.origin === 'CFS' ||
                        (formData.locId === 'INMUN1' && ['F', 'R'].includes(formData.origin))) && (
                        <>
                          <div className="form-group">
                            <label>Vehicle No</label>
                            <input
                              type="text"
                              className="form-control"
                              value={container.vehicleNo}
                              onChange={(e) => handleFormDataChange('vehicleNo', e.target.value, containerIndex)}
                            />
                          </div>

                          <div className="form-group">
                            <label>Driver License No</label>
                            <input
                              type="text"
                              className="form-control"
                              value={container.driverLicNo}
                              onChange={(e) => handleFormDataChange('driverLicNo', e.target.value, containerIndex)}
                            />
                          </div>

                          {/* Driver Name - Only show for CFS origin */}
                          {formData.origin === 'CFS' && (
                            <div className="form-group">
                              <label>
                                Driver Name {renderFieldIndicator('driverNm', containerIndex)}
                              </label>
                              <input
                                type="text"
                                className={`form-control ${hasFieldError('driverNm', containerIndex) ? 'error' : ''}`}
                                value={container.driverNm}
                                onChange={(e) => handleFormDataChange('driverNm', e.target.value, containerIndex)}
                              />
                              {hasFieldError('driverNm', containerIndex) && (
                                <div className="error-text">{getFieldError('driverNm', containerIndex)}</div>
                              )}
                            </div>
                          )}

                          <div className="form-group">
                            <label>Haulier</label>
                            <input
                              type="text"
                              className="form-control"
                              value={container.haulier}
                              onChange={(e) => handleFormDataChange('haulier', e.target.value, containerIndex)}
                            />
                          </div>
                        </>
                      )}

                      {/* Commodity Details */}
                      {formData.formType === 'F11' && (
                        <>
                          <div className="form-group">
                            <label>HSN Code</label>
                            <input
                              type="text"
                              className="form-control"
                              value={container.hsnCode}
                              onChange={(e) => handleFormDataChange('hsnCode', e.target.value, containerIndex)}
                            />
                          </div>

                          <div className="form-group">
                            <label>Commodity Name</label>
                            <input
                              type="text"
                              className="form-control"
                              value={container.commodityName}
                              onChange={(e) => handleFormDataChange('commodityName', e.target.value, containerIndex)}
                            />
                          </div>
                        </>
                      )}

                      {/* Shipping Instruction No for MSC - Container level */}
                      {formData.bnfCode?.toUpperCase() === 'MSCU' && (
                        <div className="form-group">
                          <label>
                            Shipping Instruction No {renderFieldIndicator('SHIP_INSTRUCT_NO', containerIndex)}
                          </label>
                          <input
                            type="text"
                            className="form-control"
                            value={container.SHIP_INSTRUCT_NO}
                            onChange={(e) => handleFormDataChange('SHIP_INSTRUCT_NO', e.target.value, containerIndex)}
                          />
                        </div>
                      )}

                      {/* CHA Remarks */}
                      <div className="form-group">
                        <label>CHA Remarks</label>
                        <textarea
                          className="form-control"
                          value={container.chaRemarks}
                          onChange={(e) => handleFormDataChange('chaRemarks', e.target.value, containerIndex)}
                          rows={2}
                        />
                      </div>
                    </div>

                    {/* Shipping Bill Details - Only show for certain locations */}
                    {needsNhavashevaCodeValidation(formData) && (
                      <div className="mt-3">
                        <div className="section-header">Shipping Bill Details (Required)</div>
                        <div className="form-grid">
                          <div className="form-group">
                            <label>
                              Shipping Bill/Invoice No {renderFieldIndicator('shipBillInvNo', containerIndex)}
                            </label>
                            <input
                              type="text"
                              className={`form-control ${
                                hasFieldError('shipBillInvNo', containerIndex) ? 'error' : ''
                              }`}
                              value={container.sbDtlsVo[0].shipBillInvNo}
                              onChange={(e) =>
                                handleFormDataChange('sbDtlsVo', e.target.value, containerIndex, 'shipBillInvNo')
                              }
                            />
                            {hasFieldError('shipBillInvNo', containerIndex) && (
                              <div className="error-text">{getFieldError('shipBillInvNo', containerIndex)}</div>
                            )}
                          </div>

                          <div className="form-group">
                            <label>Shipping Bill Date</label>
                            <input
                              type="date"
                              className="form-control"
                              value={container.sbDtlsVo[0].shipBillDt}
                              onChange={(e) =>
                                handleFormDataChange('sbDtlsVo', e.target.value, containerIndex, 'shipBillDt')
                              }
                            />
                          </div>

                          <div className="form-group">
                            <label>LEO No</label>
                            <input
                              type="text"
                              className="form-control"
                              value={container.sbDtlsVo[0].leoNo}
                              onChange={(e) =>
                                handleFormDataChange('sbDtlsVo', e.target.value, containerIndex, 'leoNo')
                              }
                            />
                          </div>

                          <div className="form-group">
                            <label>LEO Date</label>
                            <input
                              type="date"
                              className="form-control"
                              value={container.sbDtlsVo[0].leoDt}
                              onChange={(e) =>
                                handleFormDataChange('sbDtlsVo', e.target.value, containerIndex, 'leoDt')
                              }
                            />
                          </div>

                          <div className="form-group">
                            <label>CHA Name</label>
                            <input
                              type="text"
                              className="form-control"
                              value={container.sbDtlsVo[0].chaNm}
                              onChange={(e) =>
                                handleFormDataChange('sbDtlsVo', e.target.value, containerIndex, 'chaNm')
                              }
                            />
                          </div>

                          <div className="form-group">
                            <label>CHA PAN</label>
                            <input
                              type="text"
                              className="form-control"
                              value={container.sbDtlsVo[0].chaPan}
                              onChange={(e) =>
                                handleFormDataChange('sbDtlsVo', e.target.value, containerIndex, 'chaPan')
                              }
                            />
                          </div>

                          <div className="form-group">
                            <label>Exporter Name</label>
                            <input
                              type="text"
                              className="form-control"
                              value={container.sbDtlsVo[0].exporterNm}
                              onChange={(e) =>
                                handleFormDataChange('sbDtlsVo', e.target.value, containerIndex, 'exporterNm')
                              }
                            />
                          </div>

                          <div className="form-group">
                            <label>Exporter IEC</label>
                            <input
                              type="text"
                              className="form-control"
                              value={container.sbDtlsVo[0].exporterIec}
                              onChange={(e) =>
                                handleFormDataChange('sbDtlsVo', e.target.value, containerIndex, 'exporterIec')
                              }
                            />
                          </div>

                          <div className="form-group">
                            <label>No of Packages</label>
                            <input
                              type="number"
                              className="form-control"
                              value={container.sbDtlsVo[0].noOfPkg}
                              onChange={(e) =>
                                handleFormDataChange('sbDtlsVo', e.target.value, containerIndex, 'noOfPkg')
                              }
                            />
                          </div>
                        </div>
                      </div>
                    )}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* ATTACHMENTS SECTION */}
        <div className="panel">
          <div
            className="panel-title d-flex justify-between"
            onClick={() => toggleSection('attachments')}
            style={{ cursor: 'pointer' }}
          >
            <div className="d-flex gap-2">
              <span>Attachments</span>
              <span className="badge badge-info">{formData.attachments.length} File(s)</span>
            </div>
            <span>
              {expandedSections.attachments ? (
                <ExpandLessIcon fontSize="small" />
              ) : (
                <ExpandMoreIcon fontSize="small" />
              )}
            </span>
          </div>

          {expandedSections.attachments && (
            <div>
              {/* Required Attachments Info */}
              {requiredAttachments.length > 0 && (
                <div className="alert alert-info mb-3">
                  <InfoIcon fontSize="small" />
                  <div>
                    <strong>Required Attachments:</strong>
                    <ul>
                      {requiredAttachments
                        .filter((att) => att.required)
                        .map((att, index) => (
                          <li key={index}>{att.name}</li>
                        ))}
                    </ul>
                  </div>
                </div>
              )}

              {/* Upload Button */}
              <div className="mb-3">
                <input
                  type="file"
                  id="attachmentUpload"
                  accept=".pdf"
                  multiple
                  style={{ display: 'none' }}
                  onChange={handleAttachmentUpload}
                />
                <label htmlFor="attachmentUpload" className="btn btn-primary">
                  <CloudUploadIcon fontSize="small" /> Upload Attachment
                </label>
              </div>

              {/* Attachment List */}
              {formData.attachments.length > 0 && (
                <div className="attachment-list">
                  {formData.attachments.map((attachment, index) => (
                    <div key={index} className="attachment-item">
                      <div className="attachment-info">
                        <AttachFileIcon fontSize="small" />
                        <div>
                          <div className="attachment-name">{attachment.name}</div>
                          <div className="attachment-size">{formatFileSize(attachment.size)}</div>
                        </div>
                      </div>
                      <div className="attachment-actions">
                        <select
                          className="form-control"
                          value={attachment.title}
                          onChange={(e) => handleAttachmentTitleChange(index, e.target.value)}
                        >
                          <option value="">Select Title</option>
                          {Object.entries(getRequiredAttachments(formData)).map(([key, value]) => (
                            <option key={value.code} value={value.code}>
                              {value.name}
                            </option>
                          ))}
                        </select>
                        <button className="btn btn-icon btn-danger" onClick={() => handleRemoveAttachment(index)}>
                          <DeleteIcon fontSize="small" />
                        </button>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
        </div>
      </div>

      {/* Form Actions */}
      <div className="d-flex justify-end gap-2">
        <button
          className="btn btn-outline"
          onClick={() => {
            setFormData(initialFormState);
            setValidationErrors({});
            setError('');
            setSuccess('');
          }}
          disabled={submitting}
        >
          Reset
        </button>
        <button
          className="btn btn-primary"
          onClick={handleSubmit}
          disabled={submitting || !masterDataLoaded}
        >
          {submitting ? (
            <>
              <span className="spinner"></span> Submitting...
            </>
          ) : (
            <>
              <SendIcon fontSize="small" /> Submit Form 13
            </>
          )}
        </button>
      </div>
    </div>
  );
};

export default Form13;
